#!/bin/bash
havend --testnet --out-peers 64 --detach
sleep 30
cd /src/haven-block-explorer/build
./xmrblocks -b /root/.haven/testnet/lmdb/ -d http://127.0.0.1:27750 --mainnet-url=https://explorer.havenprotocol.org --enable-emission-monitor=1 --testnet

